### ISSUE TITLE
please change nginx to chef_nginx

### ISSUE THREAD

**Issue by runningman84** [sous-chefs/grafana#148]
The requirement of nginx creates a lot of problems (requires old ohai and other stuff). Please use chef_nginx instead:
https://github.com/chef-cookbooks/chef_nginx

**Comment by JonathanTron** [comment]
Hi @runningman84,

thanks for raising the issue. It seems updating to the chef community maintained version is the way to go.

Would you be able to send a PR for this?

**Comment by runningman84** [comment]
@JonathanTron is there any chance to get a release soon?

**Comment by JonathanTron** [comment]
I've received a lot of question regarding a release. I would like to, but not without at least some testing. There were a lot of changes integrated since the last release and I've not yet been able to take the time to ensure they all work as expected. 

So any help on this front would help me with releasing a new version faster.

**Comment by runningman84** [comment]
what about releasing (or just raising the version in the metadata) something here in github like a soft launch... wait a few weeks and update in supermarket afterwards?

**Comment by lanyonm** [comment]
I have the same concerns as @JonathanTron. I feel that there's quite a bit of upgrade documentation and testing we'd need to perform before even calling something a beta release.

I know my organization continues to use an older version of the cookbook because the lwrp usage changed since the last major release, and we'd already augmented the cookbook for everything we needed. We'd like to upgrade, but the path would need to be better documented.

There are so many active users on the 2.x cookbook release, I think it'd be irresponsible to release a major version upgrade without a documented upgrade path.

**Comment by runningman84** [comment]
is there anything which speaks against merging my pull request?

**Comment by sean-kang** [comment]
nginx 2.7.6 cookbook is causing dependency issues in our environment because it is dependent on outdated cookbooks such as ohai ~> 2.0 and apt ~> 2.2. I am trying to switch to chef-nginx and found out grafana cookbook is also dependent on nginx cookbook.

**Comment by reid-harrison** [comment]
@JonathanTron, I would like to raise the argument against depending on any nginx cookbook as that is not a core dependency of Grafana. Coupling this cookbook with an nginx cookbook (even if no webserver is desired) just adds unnecessary brittleness.

Due to conflicts with other cookbooks in my run_list, I have to maintain my own version of chef-grafana with the nginx dependency removed.

**Comment by runningman84** [comment]
Good point just recommended a wrapper for the nginx stuff and remove the dependency completely.

**Comment by JonathanTron** [comment]
The dependency has been changed to `chef_nginx` in https://github.com/JonathanTron/chef-grafana/pull/153... I'll open a new issue to discuss removing entirely the nginx dependency.
