### ISSUE TITLE
Import Dashboard from Grafana.com

### ISSUE THREAD

**Issue by shubhamc183** [sous-chefs/grafana#366]
## :person_frowning: Import Dashboard from Grafana.com

A way to import dashboard from Grafana.com directly as I have to manually download them into the disk and load them. Also, I miss if any updates are given.

For example, by specifying the ID number I can directly import it.
https://grafana.com/grafana/dashboards/1860

## :grey_question: Possible Solution

Using the same /api/dashboards/import API

## :arrow_heading_up: Describe alternatives you've considered
https://community.grafana.com/t/is-there-an-equivalent-http-api-to-import-a-dashboard-from-grafana-com/9581/2

**Comment by axelrtgs** [comment]
The only bit that would be complicated is the selection of datasource. it seems to be required in order to import the dashboard. the example works because the datasource is the same and known for all the dashboards. How do you propose to do the datasource selection? One option is to let the user provide it as a parameter to the dashboard import resource and the users would have to be diligent in providing it for any dashboard they want to import.

I am likely going to be doing some work on Grafana tomorrow(today) so if that works for you I could throw something together if its not too long or complicated and time permits.

**Comment by shubhamc183** [comment]
Sorry, for the late reply @axelrtgs .

But it looks like _selection of datasource_ may not be required in order to import a dashboard as [`/api/dashboards/db`](https://grafana.com/docs/grafana/latest/http_api/dashboard/#create--update-dashboard) doesn't accept any parameter `datasource`.

Instead of `source` we can have a var `grafana_dasboard_id`
```
grafana_dashboard 'test-dash' do
  dashboard(
    grafana_dasboard_id: '1234',
    overwrite: true,
    folder: 'My Folder'
  )
end
```

But not sure to use instead of 'test-dash'!

**Comment by shubhamc183** [comment]
Closing this ticket due to inactivity.

**Comment by Fuuzetsu** [comment]
Not sure what kind of activity there would have to be here.

This is still very much desirable.
